import { Link } from 'react-router-dom';
import { useTheme } from '../context/ThemeContext';
import logoSmartAgenda from '../assets/smartagenda-logo.png';
import logoSmartAgendaDark from '../assets/smartagenda-logo-dark.png';

const citas = [['09:00','Consulta general','Juan Pérez','ok'],['10:30','Control de seguimiento','Laura Fernández','pending'],['12:00','Horario disponible','Listo para reservar','free'],['16:00','Consulta general','Sofía Rojas','ok']];
const rubros = [['fa-scissors','Peluquerías y barberías','Servicios, duración y agenda por profesional.'],['fa-stethoscope','Consultorios','Seguimiento y disponibilidad en tiempo real.'],['fa-paw','Veterinarias','Una agenda clara para cada atención diaria.'],['fa-dumbbell','Entrenadores','Sesiones, clases y clientes organizados.']];

export default function Landing() {
  const { theme, toggleTheme } = useTheme();
  return <div className="landing-page landing-v2">
    <nav className="landing-nav"><Link to="/" className="landing-nav-brand"><img className="logo-light" src={logoSmartAgenda} alt="SmartAgenda Pro" /><img className="logo-dark" src={logoSmartAgendaDark} alt="" /></Link><div className="landing-nav-links"><a href="#como-funciona">Cómo funciona</a><a href="#rubros">Soluciones</a><a href="#resultados">Resultados</a></div><div className="landing-nav-actions"><button className="theme-toggle" onClick={toggleTheme}><i className={`fas fa-${theme === 'dark' ? 'sun' : 'moon'}`} /></button><Link to="/login" className="landing-login">Ingresar</Link><Link to="/register" className="landing-join">Registrar</Link></div></nav>
    <main><section className="landing-hero" id="como-funciona"><div className="landing-hero-text"><span className="landing-kicker"><i /> AGENDA ONLINE PARA PROFESIONALES</span><h1>Tu agenda de trabajo,<br /><em>ordenada de verdad.</em></h1><p>Reservas, disponibilidad, clientes y métricas en un solo lugar. Dedicá menos tiempo a coordinar y más a atender.</p><div className="landing-hero-btns"><Link to="/register" className="btn-hero-primary">Crear mi agenda <i className="fas fa-arrow-right" /></Link></div><p className="hero-note"><i className="fas fa-check-circle" /> Configurá tus horarios y empezá a recibir reservas.</p></div>
      <div className="agenda-preview"><header><div><small>MARTES, 24 DE SEPTIEMBRE</small><h3>Agenda de hoy</h3></div><button><i className="fas fa-ellipsis-h" /></button></header><div className="preview-summary"><div><span>Turnos de hoy</span><b>8</b></div><div><span>Ocupación</span><b>76%</b></div><div><span>Próximo</span><b>09:00</b></div></div><div className="preview-list">{citas.map(([hora,servicio,cliente,estado])=><div className={`preview-slot ${estado}`} key={hora}><time>{hora}</time><i /><div><b>{servicio}</b><span>{cliente}</span></div>{estado==='pending'&&<small>Por confirmar</small>}{estado==='free'&&<button>+ Agendar</button>}</div>)}</div><footer><i className="fas fa-bell" /> Se liberó un horario: hay 2 clientes en lista de espera</footer></div></section>
      <section className="landing-results" id="resultados"><div><small>MENOS COORDINACIÓN MANUAL</small><strong>Todo lo importante, visible en segundos.</strong></div>{[['fa-calendar-day','Disponibilidad real','Los clientes solo ven horarios libres.'],['fa-bell','Cancelaciones aprovechadas','Lista de espera para no perder turnos.'],['fa-chart-line','Mejores decisiones','Reportes claros para tu negocio.']].map(([icon,titulo,desc])=><article key={titulo}><i className={`fas ${icon}`} /><p><b>{titulo}</b>{desc}</p></article>)}</section>
      <section className="landing-rubros" id="rubros"><div className="section-intro"><span className="landing-kicker">UN SISTEMA, DISTINTAS FORMAS DE TRABAJAR</span><h2>Una agenda que se adapta a tu forma de atender.</h2></div><div className="rubros-grid">{rubros.map(([icon,titulo,desc])=><article className="rubro-card" key={titulo}><i className={`fas ${icon}`} /><h3>{titulo}</h3><p>{desc}</p><span>Ver solución <i className="fas fa-arrow-right" /></span></article>)}</div></section>
      <section className="landing-cta"><div><span className="landing-kicker">EMPEZÁ HOY</span><h2>Que coordinar turnos deje de ser tu trabajo extra.</h2><p>Creá tu cuenta, configurá horarios y empezá a recibir reservas.</p></div><Link to="/register" className="btn-hero-primary">Crear cuenta gratis <i className="fas fa-arrow-right" /></Link></section></main>
    <footer className="landing-footer"><div className="footer-logo"><img className="logo-light" src={logoSmartAgenda} alt="SmartAgenda Pro" /><img className="logo-dark" src={logoSmartAgendaDark} alt="" /></div><p>Gestión de turnos para profesionales independientes.</p><p>© 2026</p></footer>
  </div>;
}
