package com.smartagenda.api;

import jakarta.servlet.http.HttpSession;
import java.time.LocalTime;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/lista-espera") public class ListaEsperaController {
 private final JdbcTemplate jdbc; public ListaEsperaController(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @GetMapping public List<Map<String,Object>> list(HttpSession s){Map<String,Object>u=SessionSupport.role(s,"Cliente"); vencer();return jdbc.queryForList("SELECT le.*,p.nombreNegocio,sv.nombre servicio_nombre,t.fecha fechaOferta,t.horaInicio horaOferta FROM lista_espera le JOIN profesional p ON p.idProfesional=le.idProfesional JOIN servicio sv ON sv.idServicio=le.idServicio LEFT JOIN turno t ON t.idTurno=le.idTurnoOfertado WHERE le.idCliente=? ORDER BY FIELD(le.estado,'ofertada','esperando','aceptada','vencida','cancelada'),le.fechaSolicitud DESC",SessionSupport.intValue(u,"idUsuario"));}
 @PostMapping public Map<String,Object> create(@RequestBody Map<String,Object>b,HttpSession s){Map<String,Object>u=SessionSupport.role(s,"Cliente");int p=AuthController.number(b,"idProfesional",0),serv=AuthController.number(b,"idServicio",0);String fecha=AuthController.text(b,"fecha"),desde=AuthController.textOr(b,"horaDesde",""),hasta=AuthController.textOr(b,"horaHasta","");if(p<=0||serv<=0||fecha.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"Profesional, servicio y fecha son requeridos");if(!desde.isBlank()&&!hasta.isBlank()&&hasta.compareTo(desde)<0)throw new ApiException(HttpStatus.BAD_REQUEST,"El rango horario no es válido");if(jdbc.queryForObject("SELECT COUNT(*) FROM servicio WHERE idServicio=? AND idProfesional=?",Integer.class,serv,p)==0)throw new ApiException(HttpStatus.NOT_FOUND,"Servicio no encontrado");jdbc.update("INSERT INTO lista_espera(fechaDeseada,horaDesde,horaHasta,idCliente,idProfesional,idServicio) VALUES(?,?,?,?,?,?)",fecha,desde.isBlank()?null:desde,hasta.isBlank()?null:hasta,SessionSupport.intValue(u,"idUsuario"),p,serv);return Map.of("message","Te anotaste en la lista de espera","id",jdbc.queryForObject("SELECT LAST_INSERT_ID()",Integer.class));}
 @PutMapping public Map<String,String> update(@RequestBody Map<String,Object>b,HttpSession s){Map<String,Object>u=SessionSupport.role(s,"Cliente");vencer();int id=AuthController.number(b,"idListaEspera",0);String accion=AuthController.text(b,"accion");Map<String,Object>e;try{e=jdbc.queryForMap("SELECT * FROM lista_espera WHERE idListaEspera=? AND idCliente=?",id,SessionSupport.intValue(u,"idUsuario"));}catch(org.springframework.dao.EmptyResultDataAccessException x){throw new ApiException(HttpStatus.NOT_FOUND,"Solicitud no encontrada");}if("cancelar".equals(accion)){jdbc.update("UPDATE lista_espera SET estado='cancelada' WHERE idListaEspera=? AND estado IN ('esperando','ofertada')",id);return Map.of("message","Solicitud cancelada");}if(!"aceptar".equals(accion)||!"ofertada".equals(e.get("estado")))throw new ApiException(HttpStatus.BAD_REQUEST,"Acción no válida");Map<String,Object>t=jdbc.queryForMap("SELECT * FROM turno WHERE idTurno=?",e.get("idTurnoOfertado"));if(!"cancelado".equals(t.get("estado")))throw new ApiException(HttpStatus.CONFLICT,"El horario ya no está disponible");jdbc.update("INSERT INTO turno(fecha,horaInicio,horaFin,estado,idCliente,idServicio,idProfesional) VALUES(?,?,?,'pendiente',?,?,?)",t.get("fecha"),t.get("horaInicio"),t.get("horaFin"),SessionSupport.intValue(u,"idUsuario"),t.get("idServicio"),t.get("idProfesional"));jdbc.update("UPDATE lista_espera SET estado='aceptada' WHERE idListaEspera=?",id);return Map.of("message","Turno recuperado y reservado correctamente");}
 private void vencer(){jdbc.update("UPDATE lista_espera SET estado='vencida' WHERE estado='ofertada' AND fechaExpiracion<NOW()");}
}
